
services:
  python-service-test:
    build:
      context: ./backend/python-service
      dockerfile: Dockerfile
      args:
        entry_point: main_test
    ports:
      - "5000:5000"
    volumes:
      - ./backend/python-service:/app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres-test:5432/financial_test_db
      - ENV=testing
    depends_on:
      - postgres-test
    command: sh -c "pytest -xvs ./tests && uvicorn app.main_test:app --host 0.0.0.0 --port 5000 --reload"

  postgres-test:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=financial_test_db
    ports:
      - "5433:5432"  # Different port to avoid conflicts with dev environment
    volumes:
      - postgres_test_data:/var/lib/postgresql/data

volumes:
  postgres_test_data: