services:
  stock-service:
    build:
      context: ./stock-service
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    env_file:
      - ./stock-service/.env
    environment:
      - FINNHUB_API_KEY=${FINNHUB_API_KEY}
      - FINNHUB_BASE_URL=${FINNHUB_BASE_URL}
      - ALPACA_TEST_URL=wss://stream.data.alpaca.markets/v2/test
      - ALPACA_API_KEY=${ALPACA_API_KEY}
      - ALPACA_API_SECRET=${ALPACA_API_SECRET}
      - ALPHA_VANTAGE_API_KEY=${ALPHA_VANTAGE_API_KEY}
    volumes:
      - ./stock-service/logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  portfolio-service:
    build:
      context: ./portfolio-service
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    env_file:
      - ./portfolio-service/.env
    environment:
      - DATABASE_URL=${SUPABASE_DATABASE_URL}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

volumes:
  pip_cache: